# Enable RTT logging
CONFIG_LOG=y
CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_UART_CONSOLE=n
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y

CONFIG_MAIN_STACK_SIZE=4096

# Enable the NPM13XX charger and regulator
CONFIG_REGULATOR=y
CONFIG_NPM13XX_CHARGER=y
CONFIG_REGULATOR_NPM13XX=y
CONFIG_NPM13XX_CHARGER=y

# Enable the fuel gauge
CONFIG_SENSOR=y
CONFIG_NRF_FUEL_GAUGE=y

# Enable GPIO, I2C, SPI, and PWM drivers
CONFIG_GPIO=y

CONFIG_I2C=y

CONFIG_SPI=y

CONFIG_PWM=y

# Enable the LED strip driver
CONFIG_LED_STRIP=y
CONFIG_LED_STRIP_LOG_LEVEL_DBG=y